[package]
name = "zedmartzombiefest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 1

[dependencies]
bevy = "0.13"
bevy_renet = "0.0.11"
rand = "0.8.5"
rand_distr = "0.4.3"
